"""Add_relationship sprovider_transaction.

Revision ID: 016f508b4cc2
Revises: 76cf37e8b4a1
Create Date: 2018-09-05 11:36:04.824875

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '016f508b4cc2'
down_revision = '76cf37e8b4a1'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('transactions', sa.Column('sprovider_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'transactions', 'sproviders', ['sprovider_id'], ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'transactions', type_='foreignkey')
    op.drop_column('transactions', 'sprovider_id')
    # ### end Alembic commands ###
