"""Add identifier attr for Transaction

Revision ID: 76cf37e8b4a1
Revises: 58b7ce986aab
Create Date: 2018-09-05 09:53:27.630702

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '76cf37e8b4a1'
down_revision = '58b7ce986aab'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('transactions', sa.Column('identifier', sa.String(), nullable=False))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('transactions', 'identifier')
    # ### end Alembic commands ###
