"""switch biginterger to string since too big for db

Revision ID: aa0ff4be9494
Revises: 016f508b4cc2
Create Date: 2018-09-05 15:56:08.010563

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'aa0ff4be9494'
down_revision = '016f508b4cc2'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('sproviders', 'd',
               existing_type=sa.BIGINT(),
               type_=sa.String(),
               existing_nullable=False)
    op.alter_column('sproviders', 'e',
               existing_type=sa.BIGINT(),
               type_=sa.String(),
               existing_nullable=False)
    op.alter_column('sproviders', 'n',
               existing_type=sa.BIGINT(),
               type_=sa.String(),
               existing_nullable=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('sproviders', 'n',
               existing_type=sa.String(),
               type_=sa.BIGINT(),
               existing_nullable=False)
    op.alter_column('sproviders', 'e',
               existing_type=sa.String(),
               type_=sa.BIGINT(),
               existing_nullable=False)
    op.alter_column('sproviders', 'd',
               existing_type=sa.String(),
               type_=sa.BIGINT(),
               existing_nullable=False)
    # ### end Alembic commands ###
