"""Just need prikey, pubkey for sprovider

Revision ID: debce9abad28
Revises: aa0ff4be9494
Create Date: 2018-09-10 19:59:42.631742

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'debce9abad28'
down_revision = 'aa0ff4be9494'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('sproviders', 'n')
    op.drop_column('sproviders', 'd')
    op.drop_column('sproviders', 'e')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('sproviders', sa.Column('e', sa.VARCHAR(), autoincrement=False, nullable=False))
    op.add_column('sproviders', sa.Column('d', sa.VARCHAR(), autoincrement=False, nullable=False))
    op.add_column('sproviders', sa.Column('n', sa.VARCHAR(), autoincrement=False, nullable=False))
    # ### end Alembic commands ###
